name: scroll_to_index
description: Scroll to a specific child of any scrollable widget in Flutter
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter